# Generated by Django 4.2.4 on 2023-08-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('pontosturisticos', '0003_pontosturisticos_avaliacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='enderecos',
            field=models.ManyToManyField(to='enderecos.endereco'),
        ),
    ]
