# Generated by Django 4.2.4 on 2023-08-02 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('pontosturisticos', '0005_rename_enderecos_pontosturisticos_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontosturisticos',
            name='endereco',
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco'),
            preserve_default=False,
        ),
    ]
